# -*- coding: utf-8 -*-
"""23CSM2R22_WDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cg3d5EPrRs_ZYO2yMh0xNoY2FZvn_zbf
"""

subjects=['student','teacher','admin']
objects=['User_ID','Grading','Fee Payment','Course Enrollment']
acm=[['r','r','r','rw'],['r','rw','r','r'],['rwd','r','rw','rd']]
user=int(input("Who are you?\n1.Student \n2.Teacher \n3.Admin\n\n"))
task=int(input("What do you want to do?\n1.Useridentification \n2.Grading \n3.Fee Payment \n4.Course Enrollment\n\n"))
rights=input("What will you perform?\nr=read \nw=write \nd=delete\n\n")
flag=False
if rights in (acm[user-1][task-1]):
    print("Permission granted")
    flag=True
if not flag:
    print("Permission denied")

#capability list
user=int(input("\n\nWho are you?\n1.Student \n2.Teacher \n3.Admin\n\n"))
print("Capability list is as below:-")
for i in range(len(objects)):
    print(objects[i],acm[user-1][i])

#access list
task=int(input("\n\n\nWhat do you want to do?\n1.Useridentification \n2.Grading \n3.Fee Payment \n4.Course Enrollment\n\n"))
print("Access list is as below:-")
for i in range(len(subjects)):
    print(subjects[i],acm[i][task-1])

import os

subjects=['student','teacher','admin']
objects=['/WDS/User_ID.txt','/WDS/Grading.txt','/WDS/FeePayment.txt','/WDS/CourseEnrollment.txt']
#1objects=['User_ID','Grading','Fee Payment','Course Enrollment']
acl=[['r','r','r','rw'],['r','rw','r','r'],['rwd','r','rw','rd']]
user=int(input("Who are you?\n1.Student \n2.Teacher \n3.Admin\n\n"))
task=int(input("What do you want to do?\n1.Useridentification \n2.Grading \n3.Fee Payment \n4.Course Enrollment\n\n"))
rights=input("What will you perform?\nr=read \nw=write \nd=delete\n\n")
flag=False
if rights in (acl[user-1][task-1]):
    print("Permission granted")
    if rights=='r':
      try:
        f = open(objects[task-1],'r')
      except IOError:
        f = open(objects[task-1], 'x')

        f = open(objects[task-1], "r")
        f.read()
    elif rights=='w':
        f = open(objects[task-1], "a+")
        f.write("Now the file has more content!")
        #f.close()
    elif rights=='d':
        try:
         os.remove(objects[task-1])
        except IOError:
          print("File does not exists")
    flag=True
if not flag:
    print("Permission denied")

'''
for capability list
user=int(input("Who are you?\n1.Student \n2.Teacher \n3.Admin\n\n"))
for i in range(len(objects)):
    print(objects[i],acl[user-1][i])


for access list
task=int(input("What do you want to do?\n1.Useridentification \n2.Grading \n3.Fee Payment \n4.Course Enrollment\n\n"))
for i in range(len(subjects)):
    print(subjects[i],acl[i][task-1])
'''